image: integratedexperts/circleci2-builder

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://localhost:2375
  COMPOSE_INTERACTIVE_NO_CLI: 1

stages:
  - pull
  - build
#  - test
#  - deploy

pull:
  stage: pull
  artifacts:
    untracked: true
  script:
  - echo "Pulling latest GovCMS images"
#  - export DOCKER_HOST=
  - docker info
  - ahoy pull

build:
  stage: build
  dependencies:
    - pull
  script:
  - echo "Building environment"
  - docker info
  - docker network prune -f && docker network create amazeeio-network
  - echo "VOLUME_FLAGS=cached">.env
  - ahoy up
  - docker-compose exec -T test dockerize -wait tcp://mariadb:3306 -timeout 1m
  - docker-compose exec -T test bash -c "drush si -y govcms install_configure_form.update_status_module='array(FALSE,FALSE)'"
  - docker-compose exec -T test lint-theme
  - docker-compose exec -T test behat
  - docker-compose exec -T test phpunit
#  - ahoy install

#test:lint:
#  stage: test
#  script:
#  - echo "Linting code"
#  - sleep 5
#  allow_failure: true
#
#test:phpunit:
#  stage: test
#  script:
#  - echo "Running PHPUnit tests"
#  - sleep 5
#
#test:behat:
#  stage: test
#  script:
#  - echo "Running Behat tests"
#  - sleep 5
#
#deploy:
#  stage: deploy
#  script:
#  - echo "Deploying project to Lagoon"
#  - echo "curl -X POST -d projectName=$CI_PROJECT_NAME -d branchName=$CI_COMMIT_REF_NAME http://rest2tasks-lagoon.govcms.amazee.io/deploy"
#  - curl -X POST -d projectName=$CI_PROJECT_NAME -d branchName=$CI_COMMIT_REF_NAME http://rest2tasks-lagoon.govcms.amazee.io/deploy
##  only:
##    - master
