image: integratedexperts/circleci2-builder

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://localhost:2375
  COMPOSE_INTERACTIVE_NO_CLI: 1

# @todo: Remove stages
stages:
  - build

build:
  stage: build
  dependencies:
    - pull
  script:
  - ahoy pull
  # @todo: Remove this.
  - docker network prune -f && docker network create amazeeio-network
  - echo "VOLUME_FLAGS=cached">.env
  - ahoy up
  - docker-compose exec -T test dockerize -wait tcp://mariadb:3306 -timeout 1m
  - ahoy -v install -- install_configure_form.update_status_module='array(FALSE,FALSE)'
  - ahoy lint
  - ahoy test-phpunit
  - ahoy test-behat
  artifacts:
    paths:
    - tests/behat/features/screenshots
    expire_in: 1 hour
