image: integratedexperts/circleci2-builder

services:
  - docker:dind

build:
  script:
  - export DOCKER_HOST=tcp://localhost:2375
  - docker run --name amazeeio-ssh-agent -d amazeeio/ssh-agent
  - ahoy up
  - docker-compose exec -T test dockerize -wait tcp://mariadb:3306 -timeout 1m
  - ahoy -v install -- install_configure_form.update_status_module='array(FALSE,FALSE)'
  - ahoy lint
  - ahoy test-phpunit
  - ahoy test-behat
  artifacts:
    paths:
    - tests/behat/features/screenshots
    expire_in: 1 hour
