docker-compose-yaml: docker-compose.yml

tasks:
  post-rollout:
    - run:
        name: Database updates
        command: drush updb -y
        service: cli
    - run:
        name: Clear caches
        command: drush cc all
        service: cli

environments:
  master:
    cronjobs:
      - name: drush cron
        schedule: "*/15 * * * *"
        command: 'drush cron'
        service: cli
