FROM govcmsdev/test-saas

COPY themes/ /app/profiles/govcms/themes/custom

RUN rm -Rf /app/tests/behat/features/*
COPY tests/behat/features/ /app/tests/behat/features

RUN rm -Rf /app/tests/phpunit/tests/*
COPY tests/phpunit/tests/ /app/tests/phpunit/tests
