ARG GOVCMS_IMAGE_VERSION=latest

FROM govcmslagoon/test:${GOVCMS_IMAGE_VERSION}

COPY themes/ /app/sites/default/themes/custom

RUN rm -Rf /app/tests/behat/features/*
COPY tests/behat/features/ /app/tests/behat/features

RUN rm -Rf /app/tests/phpunit/tests/*
COPY tests/phpunit/tests/ /app/tests/phpunit/tests
