ARG GOVCMS_IMAGE_VERSION=latest
FROM govcmslagoon/govcms7:${GOVCMS_IMAGE_VERSION}

COPY themes/ /app/sites/default/themes/custom

# Default application favicon this will be used for files and server
# error pages all other favicon requests will be surfaced via Drupal.
COPY favicon.ico /app
